-- MySQL Script generated by MySQL Workbench
-- seg 20 mai 2019 22:51:00 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sistemag
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistemag
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistemag` DEFAULT CHARACTER SET utf8 ;
USE `sistemag` ;

-- -----------------------------------------------------
-- Table `sistemag`.`instrutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemag`.`instrutor` (
  `cpf` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(45) NULL,
  `telefone` VARCHAR(11) NULL,
  `email` VARCHAR(45) NULL,
  `crea` VARCHAR(45) NULL,
  `valoraula` DECIMAL NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemag`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemag`.`curso` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `cargahoraria` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemag`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemag`.`turma` (
  `codturma` VARCHAR(10) NOT NULL,
  `curso` INT NULL,
  `instrutor` VARCHAR(11) NULL,
  `datainicio` DATE NULL,
  `datafim` DATE NULL,
  `valor` DECIMAL NULL,
  PRIMARY KEY (`codturma`),
  INDEX `fk_instrutor_idx` (`instrutor` ASC),
  INDEX `fk_curso_idx` (`curso` ASC),
  CONSTRAINT `fk_instrutor`
    FOREIGN KEY (`instrutor`)
    REFERENCES `sistemag`.`instrutor` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_curso`
    FOREIGN KEY (`curso`)
    REFERENCES `sistemag`.`curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemag`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemag`.`empresa` (
  `cnpj` VARCHAR(14) NOT NULL,
  `razao` VARCHAR(45) NULL,
  `inscricao` VARCHAR(45) NULL,
  `endereco` VARCHAR(45) NULL,
  `rua` VARCHAR(45) NULL,
  `numero` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `responsavel` VARCHAR(45) NULL,
  PRIMARY KEY (`cnpj`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemag`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemag`.`aluno` (
  `cpf` VARCHAR(11) NOT NULL,
  `rg` VARCHAR(45) NULL,
  `nome` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `profissao` VARCHAR(45) NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemag`.`matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemag`.`matricula` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `aluno` VARCHAR(11) NULL,
  `empresa` VARCHAR(14) NULL,
  `turma` VARCHAR(45) NULL,
  `desconto` DECIMAL NULL,
  `pagamento` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_aluno` (`aluno` ASC),
  INDEX `fk_empresa` (`empresa` ASC),
  INDEX `fk_turma` (`turma` ASC),
  CONSTRAINT `fk_aluno`
    FOREIGN KEY (`aluno`)
    REFERENCES `sistemag`.`aluno` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empresa`
    FOREIGN KEY (`empresa`)
    REFERENCES `sistemag`.`empresa` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turma`
    FOREIGN KEY (`turma`)
    REFERENCES `sistemag`.`turma` (`codturma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemag`.`certificado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemag`.`certificado` (
  `numero` INT NOT NULL,
  `matricula` INT NULL,
  PRIMARY KEY (`numero`),
  INDEX `fk_matricula_idx` (`matricula` ASC),
  CONSTRAINT `fk_matricula`
    FOREIGN KEY (`matricula`)
    REFERENCES `sistemag`.`matricula` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemag`.`custos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemag`.`custos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `luz` DECIMAL NULL,
  `agua` DECIMAL NULL,
  `aluguel` DECIMAL NULL,
  `alimento` DECIMAL NULL,
  `datainicio` DATE NULL,
  `datafim` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
