-- MySQL Script generated by MySQL Workbench
-- seg 08 jul 2019 18:50:20 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sistemag
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistemag
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistemag` DEFAULT CHARACTER SET utf8 ;
USE `sistemag` ;

-- -----------------------------------------------------
-- Table `sistemag`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemag`.`aluno` (
  `cpf` VARCHAR(11) NOT NULL,
  `rg` VARCHAR(45) NULL DEFAULT NULL,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `telefone` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `profissao` VARCHAR(45) NULL DEFAULT NULL,
  `endereco` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sistemag`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemag`.`empresa` (
  `cnpj` VARCHAR(14) NOT NULL,
  `razao` VARCHAR(45) NULL DEFAULT NULL,
  `inscricao` VARCHAR(45) NULL DEFAULT NULL,
  `endereco` VARCHAR(45) NULL DEFAULT NULL,
  `telefone` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `responsavel` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`cnpj`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sistemag`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemag`.`curso` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `cargahoraria` INT(11) NULL DEFAULT NULL,
  `descricao` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sistemag`.`instrutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemag`.`instrutor` (
  `cpf` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `telefone` VARCHAR(15) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `crea` VARCHAR(45) NULL DEFAULT NULL,
  `endereco` VARCHAR(45) NULL DEFAULT NULL,
  `valor` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sistemag`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemag`.`turma` (
  `codturma` VARCHAR(10) NOT NULL,
  `curso` INT(11) NULL DEFAULT NULL,
  `instrutor` VARCHAR(11) NULL DEFAULT NULL,
  `datainicio` DATE NULL DEFAULT NULL,
  `datafim` DATE NULL DEFAULT NULL,
  `valor` DECIMAL(10,0) NULL DEFAULT NULL,
  PRIMARY KEY (`codturma`),
  INDEX `fk_instrutor_idx` (`instrutor` ASC) VISIBLE,
  INDEX `fk_curso_idx` (`curso` ASC) VISIBLE,
  CONSTRAINT `fk_curso`
    FOREIGN KEY (`curso`)
    REFERENCES `sistemag`.`curso` (`id`),
  CONSTRAINT `fk_instrutor`
    FOREIGN KEY (`instrutor`)
    REFERENCES `sistemag`.`instrutor` (`cpf`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sistemag`.`matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemag`.`matricula` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `aluno` VARCHAR(11) NULL DEFAULT NULL,
  `empresa` VARCHAR(14) NULL DEFAULT NULL,
  `turma` VARCHAR(45) NULL DEFAULT NULL,
  `desconto` DECIMAL(10,0) NULL DEFAULT NULL,
  `pagamento` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_aluno` (`aluno` ASC) VISIBLE,
  INDEX `fk_empresa` (`empresa` ASC) VISIBLE,
  INDEX `fk_turma` (`turma` ASC) VISIBLE,
  CONSTRAINT `fk_aluno`
    FOREIGN KEY (`aluno`)
    REFERENCES `sistemag`.`aluno` (`cpf`),
  CONSTRAINT `fk_empresa`
    FOREIGN KEY (`empresa`)
    REFERENCES `sistemag`.`empresa` (`cnpj`),
  CONSTRAINT `fk_turma`
    FOREIGN KEY (`turma`)
    REFERENCES `sistemag`.`turma` (`codturma`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sistemag`.`certificado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemag`.`certificado` (
  `numero` INT(11) NOT NULL,
  `matricula` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`numero`),
  INDEX `fk_matricula_idx` (`matricula` ASC) VISIBLE,
  CONSTRAINT `fk_matricula`
    FOREIGN KEY (`matricula`)
    REFERENCES `sistemag`.`matricula` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sistemag`.`custos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemag`.`custos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `luz` DECIMAL(10,0) NULL DEFAULT NULL,
  `agua` DECIMAL(10,0) NULL DEFAULT NULL,
  `aluguel` DECIMAL(10,0) NULL DEFAULT NULL,
  `alimento` DECIMAL(10,0) NULL DEFAULT NULL,
  `datainicio` DATE NULL DEFAULT NULL,
  `datafim` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
